apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: optimized-baseline
    meta.helm.sh/release-namespace: llm-d-optimized-baseline
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: optimized-baseline-epp
    app.kubernetes.io/version: v1.5.0
  name: optimized-baseline
  namespace: llm-d-optimized-baseline
spec:
  default:
    checkIntervalSec: 2
    config:
      httpHealthCheck:
        port: 8000
        requestPath: /health
      type: HTTP
    timeoutSec: 2
  targetRef:
    group: inference.networking.k8s.io
    kind: InferencePool
    name: optimized-baseline
