apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    llm-d.ai/accelerator-variant: gpu
    llm-d.ai/accelerator-vendor: nvidia
    llm-d.ai/guide: optimized-baseline
    llm-d.ai/model: Qwen3-32B
  name: optimized-baseline-nvidia-gpu-vllm-sa
  namespace: llm-d-optimized-baseline
